typography_spectrum: 0.47072
color:
  brandColors:
    - '#ffffff'
    - '#0a0313'
    - '#321846'
    - '#9e9da2'
    - '#797281'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.87088
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: the constellationist
  email: theconstellationist@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e60729ed-0b8e-4006-8cf7-f1a0639f1be8.png
name: constellationist
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 3c6a7ff5-32e2-40f5-868c-ca8b62d5fe41
    url: 2016-03-01-shop.html
    name: SHOP
    type: content
favicon: null
purpose:
  - name: null
    item: null
    url: null
