name: constellationist
favicon: null
layout_spectrum: 0.79455
typography_spectrum: 0.47072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0313'
    - '#321846'
    - '#9e9da2'
    - '#797281'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.125
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
