name: constellationist
favicon: null
layout_spectrum: 0.322072
typography_spectrum: 0.47072
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C8B8C8'
    - '#100818'
    - '#607898'
    - '#8040BF'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.506756
  saturation: 0.5625
  rhythmicContrast: 0.603603
purpose:
  - name: null
    item: null
    url: null
